"""/explain <concept>: find the matching problem type, then build a VERIFIED worked example for it.

The concept explanation itself is conversation (GoatVex labels it as
explanation, not verified computation); every concrete example, number and
step comes from a generated problem that passed the full pipeline. The
example gets a write-up page and can be rendered as a video like any solution.
"""

from __future__ import annotations

import random
import re

from tutor import registry
from tutor.pipeline import run
from tutor.study.generate import verified_problem

STOP = {"the", "a", "an", "of", "to", "how", "do", "i", "what", "is", "are", "and", "in", "for", "with", "explain",
        "me", "find", "use", "using", "why", "does", "on"}


def _words(text: str) -> set[str]:
    return {w for w in re.findall(r"[a-zà-ÿ']+", text.lower()) if w not in STOP}


def match(query: str, course: str | None = None, limit: int = 3) -> list[tuple[str, float]]:
    """Problem types ranked by how well their title/keywords match the query."""
    q = query.lower()
    qw = _words(q)
    scored = []
    for name in registry.names():
        pt = registry.get(name)
        if course and pt.course != course:
            continue
        score = 0.0
        for kw in pt.keywords:
            if kw.lower() in q:
                score += 3 + len(kw.split())
        score += 1.5 * len(qw & _words(pt.title))
        score += 0.5 * len(qw & _words(" ".join(pt.keywords)))
        if name.replace("_", " ") in q:
            score += 4
        if score > 0:
            scored.append((name, score))
    return sorted(scored, key=lambda t: -t[1])[:limit]


def best_spec(query: str, course: str | None = None) -> str | None:
    """The best type, refined to a variant when the query names one ("by parts" → indefinite_integral:parts)."""
    ranked = match(query, course, 1)
    if not ranked:
        return None
    name = ranked[0][0]
    q = query.lower().replace("-", " ")
    aliases = {"parts": ("by parts", "integration by parts"), "trig_sub": ("trig sub", "trigonometric substitution"),
               "partial_fractions": ("partial fraction",), "trig_powers": ("powers of sin", "powers of cos",
                                                                           "powers of sec", "powers of tan"),
               "substitution": ("substitution", "u sub"), "lhospital": ("l'h", "lhospital", "l'hôpital"),
               "gram_schmidt": ("gram schmidt",), "diagonalize": ("diagonaliz",)}
    for variant in registry.get(name).variants:
        words = aliases.get(variant, ()) + (variant.replace("_", " "),)
        if any(w in q for w in words):
            # "trig substitution" must not fall back to plain "substitution"
            if variant == "substitution" and any(w in q for w in aliases["trig_sub"]):
                continue
            return f"{name}:{variant}"
    return name


def example(spec: str, seed: int = 0, difficulty: int = 1):
    """A verified worked example (easy numbers), written to videos/<course>/<topic>/explain-<type>-<seed>/."""
    name = spec.partition(":")[0]
    p, _ = verified_problem(spec, random.Random(seed), difficulty, slug=f"explain-{name.replace('_', '-')}-{seed}")
    p.confirmed_by_student = True  # generated by GoatVex: nothing was transcribed
    return run(p)
